// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CrudNet8WebApp.Models;

[Index("mail", Name = "UQ__Buyers__7A2129046B709502", IsUnique = true)]
public partial class Buyer
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(255)]
    public string name { get; set; }

    [Required]
    [StringLength(255)]
    public string mail { get; set; }

    [InverseProperty("buyer")]
    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}