// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CrudNet8WebApp.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(255)]
    public string name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal price { get; set; }

    public int? categoryId { get; set; }

    [InverseProperty("product")]
    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    [InverseProperty("product")]
    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    [ForeignKey("categoryId")]
    [InverseProperty("Products")]
    public virtual Category category { get; set; }
}