// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CrudNet8WebApp.Models;

[Table("Purchase")]
public partial class Purchase
{
    [Key]
    public int id { get; set; }

    public int? buyerId { get; set; }

    public int? productId { get; set; }

    public int quantity { get; set; }

    [ForeignKey("buyerId")]
    [InverseProperty("Purchases")]
    public virtual Buyer buyer { get; set; }

    [ForeignKey("productId")]
    [InverseProperty("Purchases")]
    public virtual Product product { get; set; }
}