// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CrudNet8WebApp.Models;

[Table("Stock")]
public partial class Stock
{
    [Key]
    public int id { get; set; }

    public int? productId { get; set; }

    public int quantity { get; set; }

    [ForeignKey("productId")]
    [InverseProperty("Stocks")]
    public virtual Product product { get; set; }
}