// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CrudNet8WebApp.Models;

public partial class Test_130225Context : DbContext
{
    public Test_130225Context()
    {
    }

    public Test_130225Context(DbContextOptions<Test_130225Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Buyer> Buyers { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<Stock> Stocks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Buyer>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Buyers__3213E83FBD0197AD");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Category__3213E83F01EB3A2C");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Product__3213E83F366F2E7E");

            entity.HasOne(d => d.category).WithMany(p => p.Products).HasConstraintName("FK__Product__categor__4BAC3F29");
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Purchase__3213E83F9E47C68F");

            entity.HasOne(d => d.buyer).WithMany(p => p.Purchases).HasConstraintName("FK__Purchase__buyerI__5441852A");

            entity.HasOne(d => d.product).WithMany(p => p.Purchases).HasConstraintName("FK__Purchase__produc__5535A963");
        });

        modelBuilder.Entity<Stock>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Stock__3213E83FCD514574");

            entity.HasOne(d => d.product).WithMany(p => p.Stocks).HasConstraintName("FK__Stock__productId__4E88ABD4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}